name: Linting JSONs

# This action activates whenever there is a push or pull request into the v2 branch. 
# It validates and automatically prettifys the tilt-schema.json. 

# This action works with pull requests and pushes to the v2 branch 
on:
  pull_request:
  push:
    branches:
      - 15-github-action-ci-pipeline-for-merging-the-specification # !! Update this once we merge to master !! 

jobs: 

  run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Run Python script
      run: |
        python tilt_schema/recompile.py
        git config user.name github-actions
        git config user.email github-actions@github.com
        git pull
        git add .
        git commit --allow-empty -m "combined the file"
        git push

  prettier:
    needs: run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write combined.json #, tilt-schema.json]
          prettier_options: --write tilt-schema.json
    
