name: Linting JSONs

# This action activates whenever there is a push or pull request into the v2 branch. 
# It validates and automatically prettifys the tilt-schema.json. 

# This action works with pull requests and pushes to the v2 branch 
on:
  pull_request:
  push:
    branches:
      - v2 # !! Update this once we merge to master !! 

jobs:
  prettier:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      - name: Prettify code
        uses: creyD/prettier_action@v4.3
        with:
          # This part is also where you can pass other options, for example:
          prettier_options: --write **/tilt-schema.json