name: Generating human readable TILT-schema

# Controls when the workflow will run
on:
  pull_request:
  push:
    branches:
      - master

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          # Make sure the actual branch is checked out when running on pull requests
          ref: ${{ github.head_ref }}

      
      - name: set up Python 3.8
        uses: actions/setup-python@v3
        with:
          python-version: 3.8

      - name: install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install json-schema-for-humans

      - name: generate index.html   
        run: |
          python .github/generate_schema_for_humans.py
          rm schema_doc.min.js
          mv index.html docs

      - name: use upload artifact GH-Action
        uses: actions/upload-artifact@v3.1.2
        with: 
          name: github-pages
          path: docs
            
      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Overwritten by Github Actions